n = input('Digite um valor: ')
print(n, type(n))
print(n, 'só possui números?', n.isnumeric())
print(n, 'possui números ou letras?', n.isalnum())
print(n, 'só possui letra minúscula?', n.islower())
print(n, 'só possui letras maiúsculas?', n.isupper())
print(n, 'só possui letras?',n.isalpha())
print(n, 'só tem espaços?', n.isspace())
print(n, 'está capitalizada?', n.istitle())
